=== api-evangelist/amazon-simspace-weaver/json-schema/amazon-simspace-weaver-describe-simulation-output-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-simspace-weaver/refs/heads/main/json-schema/amazon-simspace-weaver-describe-simulation-output-schema.json",
  "title": "DescribeSimulationOutput",
  "description": "DescribeSimulationOutput schema from Amazon SimSpace Weaver API",
  "type": "object",
  "properties": {
    "Arn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SimSpaceWeaverArn"
        },
        {
          "description": "The Amazon Resource Name (ARN) of the simulation. For more information about ARNs, see <a href=\"https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html\">Amazon Resource Names (ARNs)</a> in the <i>Amazon Web Services General Reference</i>."
        }
      ]
    },
    "CreationTime": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Timestamp"
        },
        {
          "description": "The time when the simulation was created, expressed as the number of seconds and milliseconds in UTC since the Unix epoch (0:0:0.000, January 1, 1970)."
        }
      ]
    },
    "Description": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Description"
        },
        {
          "description": "The description of the simulation."
        }
      ]
    },
    "ExecutionId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/UUID"
        },
        {
          "description": "A universally unique identifier (UUID) for this simulation."
        }
      ]
    },
    "LiveSimulationState": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LiveSimulationState"
        },
        {
          "description": "A collection of additional state information, such as domain and clock configuration."
        }
      ]
    },
    "LoggingConfiguration": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LoggingConfiguration"
        },
        {
          "description": "Settings that control how SimSpace Weaver handles your simulation log data."
        }
      ]
    },
    "MaximumDuration": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TimeToLiveString"
        },
        {
          "description": "The maximum running time of the simulation, specified as a number of minutes (m or M), hours (h or H), or days (d or D). The simulation stops when it reaches this limit. The maximum value is <code>14D</code>, or its equivalent in the other units. The default value is <code>14D</code>. A value equivalent to <code>0</code> makes the simulation immediately transition to <code>Stopping</code> as soon as it reaches <code>Started</code>."
        }
      ]
    },
    "Name": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SimSpaceWeaverResourceName"
        },
        {
          "description": "The name of the simulation."
        }
      ]
    },
    "RoleArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/RoleArn"
        },
        {
          "description": "The Amazon Resource Name (ARN) of the Identity and Access Management (IAM) role that the simulation assumes to perform actions. For more information about ARNs, see <a href=\"https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html\">Amazon Resource Names (ARNs)</a> in the <i>Amazon Web Services General Reference</i>. For more information about IAM roles, see <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html\">IAM roles</a> in the <i>Identity and Access Management User Guide</i>."
        }
      ]
    },
    "SchemaError": {
      "allOf": [
        {
          "$ref": "#/components/schemas/OptionalString"
        },
        {
          "deprecated": true,
          "description": "An error message that SimSpace Weaver returns only if there is a problem with the simulation schema.SchemaError is no longer used, check StartError instead."
        }
      ]
    },
    "SchemaS3Location": {
      "allOf": [
        {
          "$ref": "#/components/schemas/S3Location"
        },
        {
          "description": "The location of the simulation schema in Amazon Simple Storage Service (Amazon S3). For more information about Amazon S3, see the <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html\"> <i>Amazon Simple Storage Service User Guide</i> </a>."
        }
      ]
    },
    "SnapshotS3Location": {
      "$ref": "#/components/schemas/S3Location"
    },
    "StartError": {
      "allOf": [
        {
          "$ref": "#/components/schemas/OptionalString"
        },
        {
          "description": "An error message that SimSpace Weaver returns only if a problem occurs when the simulation is in the <code>STARTING</code> state."
        }
      ]
    },
    "Status": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SimulationStatus"
        },
        {
          "description": "The current lifecycle state of the simulation."
        }
      ]
    },
    "TargetStatus": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SimulationTargetStatus"
        },
        {
          "description": "The desired lifecycle state of the simulation."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-simspace-weaver/examples/amazon-simspace-weaver-describe-simulation-output-example.json
{
  "Arn": "arn:aws:service:us-east-1:123456789012:resource/example",
  "CreationTime": "example-value",
  "Description": "example-value",
  "ExecutionId": "example-value",
  "LiveSimulationState": "example-value",
  "LoggingConfiguration": "example-value",
  "MaximumDuration": "example-value",
  "Name": "MyResource",
  "RoleArn": "arn:aws:service:us-east-1:123456789012:resource/example",
  "SchemaError": "example-value",
  "SchemaS3Location": "example-value",
  "SnapshotS3Location": "example-value",
  "StartError": "example-value",
  "Status": "Active",
  "TargetStatus": "Active"
}
